version: 2.1

commands:
  restore_dependencies_cache:
    description: "Try to restore dependencies cache"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run: ./gradlew dependencies

  save_dependencies_cache:
    description: "Save dependencies cache"
    steps:
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

jobs:
  cache-dependencies:
    working_directory: ~/application
    docker:
      - image: circleci/openjdk:11-jdk-stretch-node-browsers
        environment:
          JAVA_TOOL_OPTIONS: "-Xmx4G"
          GRADLE_OPTS: "-Xmx4G -Dorg.gradle.daemon=false -DdisablePreDex"
          TERM: dumb
    steps:
      - checkout
      - restore_dependencies_cache
      - save_dependencies_cache
  unit-test:
    working_directory: ~/application
    docker:
      - image: circleci/openjdk:11-jdk-stretch-node-browsers
        environment:
          JAVA_TOOL_OPTIONS: "-Xmx4G"
          GRADLE_OPTS: "-Xmx4G -Dorg.gradle.daemon=false -DdisablePreDex"
          TERM: dumb
    steps:
      - checkout
      - run:
          name: Unit tests
          command: ./gradlew test -Dtest.type=unit
      - run:
          name: Save Unit Tests results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml"
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - run:
          name: Code coverage
          command: |
            ./gradlew jacocoTestReport
            ./gradlew jacocoTestCoverageVerification
            bash <(curl -s https://codecov.io/bash)
  integration-test:
    working_directory: ~/application
    docker:
      - image: circleci/openjdk:11-jdk-stretch-node-browsers
        environment:
          JAVA_TOOL_OPTIONS: "-Xmx4G"
          GRADLE_OPTS: "-Xmx4G -Dorg.gradle.daemon=false -DdisablePreDex"
          TERM: dumb
    steps:
      - checkout
      - run:
          name: Integration tests
          command: ./gradlew test -Dtest.type=integration
      - run:
          name: Save Integration Tests results
          command: |
            mkdir -p ~/junit/integration
            find . -type f -regex ".*/build/test-results/.*xml"
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/integration \;
          when: always
      - store_test_results:
          path: ~/junit/integration
      - store_artifacts:
          path: ~/junit/integration
      - run:
          name: Code coverage
          command: |
            ./gradlew jacocoTestReport
            ./gradlew jacocoTestCoverageVerification
            bash <(curl -s https://codecov.io/bash)

  lint:
    working_directory: ~/application
    docker:
      - image: circleci/openjdk:11-jdk-stretch-node-browsers
        environment:
          JAVA_TOOL_OPTIONS: "-Xmx4G"
          GRADLE_OPTS: "-Xmx4G -Dorg.gradle.daemon=false -DdisablePreDex"
          TERM: dumb
    steps:
      - checkout
      - run:
          name: Run lint
          command: ./gradlew detekt
workflows:
  "test":
    jobs:
      - cache-dependencies
      - lint
      - integration-test
      - unit-test:
          requires:
            - cache-dependencies
